replicaCount: 1

image:
  repository: pbronneberg/kiosk-browser
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  supplementalGroups:
    - 483

securityContext:
  privileged: true

termination:
  gracePeriodSeconds: 1

command:
  override: false
  executable:
    - sleep
  args:
    - "10000"
#  executable:
#    - cage
#  args:
#    - "/opt/app/cefsimple"
#    - "--"
#    - "--no-sandbox"

resources:
  requests:
    nvidia.com/gpu: 1
  limits:
    nvidia.com/gpu: 1

runtimeClassName: nvidia

livenessProbe: {}
readinessProbe: {}

nodeSelector: {}

tolerations: []

affinity: {}
