apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kiosk-browser.name" . }}
  namespace: {{ include "kiosk-browser.name" . }}
data:
  XDG_RUNTIME_DIR: "/tmp"
  NVIDIA_DRIVER_CAPABILITIES: "all"
  WLR_LIBINPUT_NO_DEVICES: "1"
  WLR_BACKENDS: "drm"
{{/*  WLR_EGL_NO_MODIFIERS: "1"*/}}
{{/*  WLR_RENDERER: "pixman"*/}}
{{/*  WLR_NO_HARDWARE_CURSORS: "1"*/}}
{{/*  WLR_RENDERER_FORCE_SOFTWARE: "1"*/}}
{{/*  WLR_RENDERER_ALLOW_SOFTWARE: "1"*/}}
{{/*  WLR_DRM_NO_ATOMIC: "1"*/}}
